tbl_perc_viagens_monitoramento = [
    {"field": "vec_num_id", "headerName": "VEÍCULO", "minWidth": 150},
    {"field": "vec_model", "headerName": "MODELO", "minWidth": 300, "type": ["text"]},
    {
        "field": "media_consumo_por_km",
        "headerName": "Média km/L",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "filter": "agNumberColumnFilter",
        "maxWidth": 150,
        "type": ["numericColumn"],
    },
    {"field": "total_viagens", "headerName": "# Viagens", "minWidth": 150, "type": ["numericColumn"]},
    {"field": "total_status_regular", "headerName": "# Regular", "minWidth": 150, "type": ["numericColumn"]},
    {
        "field": "total_status_suspeita_baixa_perfomance",
        "headerName": "# Suspeita",
        "minWidth": 150,
        "type": ["numericColumn"],
    },
    {"field": "total_status_baixa_performance", "headerName": "# Baixo", "minWidth": 150, "type": ["numericColumn"]},
    {"field": "total_status_erro_telemetria", "headerName": "# Erro", "minWidth": 150, "type": ["numericColumn"]},
    {"field": "percentual_regular", "headerName": "% Viagens Regular", "minWidth": 150, "type": ["numericColumn"]},
    {
        "field": "percentual_suspeita_baixa_perfomance",
        "headerName": "% Viagens Suspeita",
        "minWidth": 150,
        "type": ["numericColumn"],
    },
    {
        "field": "percentual_baixa_performance",
        "headerName": "% Viagens Baixo",
        "minWidth": 150,
        "type": ["numericColumn"],
    },
    {"field": "percentual_erro_telemetria", "headerName": "% Viagens Erro", "minWidth": 150, "type": ["numericColumn"]},
]

tbl_detalhamento_viagens_monitoramento = [
    {"field": "dia_label", "headerName": "DIA", "minWidth": 150},
    {"field": "slot_horario", "headerName": "SLOT", "minWidth": 100, "type": ["text"]},
    {"field": "encontrou_numero_linha", "headerName": "LINHA", "minWidth": 100, "type": ["text"]},
    {"field": "encontrou_numero_sublinha", "headerName": "SUBLINHA", "minWidth": 100, "type": ["text"]},
    {"field": "encontrou_sentido_linha", "headerName": "SENTIDO", "minWidth": 100, "type": ["text"]},
    {"field": "status_consumo", "headerName": "STATUS", "minWidth": 200, "type": ["text"]},
    {"field": "km_redondo", "headerName": "km/L", "minWidth": 100, "type": ["numericColumn"]},
    {"field": "tempo_minutos", "headerName": "Duração (min)", "minWidth": 100, "type": ["numericColumn"]},
    {"field": "hora_inicio", "headerName": "INICIO", "minWidth": 100, "type": ["text"]},
    {"field": "hora_fim", "headerName": "FIM", "minWidth": 100, "type": ["text"]},
    {"field": "n_amostras", "headerName": "Nº Amostras", "minWidth": 100, "type": ["numericColumn"]},
    {"field": "mediana", "headerName": "Mediana", "minWidth": 100, "type": ["numericColumn"]},
    {"field": "quartil_desvpadrao", "headerName": "Desv Padrão", "minWidth": 100, "type": ["numericColumn"]},
    {"field": "nome_motorista", "headerName": "Motorista", "minWidth": 200, "type": ["text"]},
]
