tbl_detalhamento_viagens_km_l = [
    {
        "field": "vec_num_id",
        "headerName": "VEÍCULO",
        "minWidth": 120,
        "maxWidth": 120,
        "pinned": "left",
    },
    {
        "field": "acao",
        "headerName": "Perfil",
        "cellRenderer": "Button",
        "cellRendererParams": {"className": "btn btn-outline-primary btn-sm"},
        "minWidth": 150,
        "pinned": "left",
    },
    {"field": "dia_label", "headerName": "DIA", "minWidth": 150},
    {"field": "vec_model", "headerName": "MODELO", "minWidth": 200},
    {
        "field": "time_slot",
        "headerName": "SLOT",
        "minWidth": 120,
        "sort": "asc",
        "sortable": True,
    },
    {"field": "encontrou_numero_linha", "headerName": "LINHA", "minWidth": 150, "type": ["text"]},
    {"field": "encontrou_numero_sublinha", "headerName": "SUBLINHA", "minWidth": 150, "type": ["text"]},
    {
        "field": "encontrou_sentido_linha",
        "headerName": "SENTIDO",
        "maxWidth": 230,
        "type": ["text"],
    },
    {
        "field": "custo_excedente",
        "headerName": "CUSTO EXCEDENTE (R$)",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "maxWidth": 200,
        "filter": "agNumberColumnFilter",
        "valueFormatter": {
            "function": "'R$ ' + (params.value.toLocaleString('pt-BR', { maximumFractionDigits: 2, minimumFractionDigits: 2 }))"
        },
        "type": ["numericColumn"],
    },
    {
        "field": "km_por_litro",
        "headerName": "CONSUMO km/L",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "filter": "agNumberColumnFilter",
        "maxWidth": 230,
        "type": ["numericColumn"],
    },
    {
        "field": "analise_diff_mediana_90_dias",
        "headerName": "DIFERENÇA KM/L - MÉDIA LINHA",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "filter": "agNumberColumnFilter",
        "maxWidth": 160,
        "type": ["numericColumn"],
    },
    {
        "field": "nome_motorista",
        "headerName": "MOTORISTA",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "minWidth": 220,
    },
    {
        "field": "velocidade_media_kmh",
        "headerName": "VELOCIDADE MÉDIA (km/h)",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "filter": "agNumberColumnFilter",
        "maxWidth": 180,
        "type": ["numericColumn"],
    },
    {
        "field": "total_comb_l",
        "headerName": "COMBUSTÍVEL GASTO (L)",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "filter": "agNumberColumnFilter",
        "maxWidth": 160,
        "type": ["numericColumn"],
    },
    {
        "field": "encontrou_tempo_viagem_minutos",
        "headerName": "DURAÇÃO DA VIAGEM (min)",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "filter": "agNumberColumnFilter",
        "maxWidth": 160,
        "type": ["numericColumn"],
    },
    {
        "field": "tamanho_linha_km_sobreposicao",
        "headerName": "DISTÂNCIA PERCORRIDA (km)",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "filter": "agNumberColumnFilter",
        "maxWidth": 160,
        "type": ["numericColumn"],
    },
    {
        "field": "vec_asset_id",
        "headerName": "ASSET ID (MIX)",
        "wrapHeaderText": True,
        "autoHeaderHeight": True,
        "maxWidth": 140,
    },
]
